DECLARE @ActivityMonitorStartMonth INT
DECLARE @ActivityMonitorStartDate NVARCHAR(MAX)
DECLARE @ActivityMonitorBeginDate DATETIME

SET @ActivityMonitorStartDate = '2013-01-30 19:50:26.037' --CAN SET A VALUE --FORMAT 'MM/DD/YYYY HH:MM:SS:mmm' EG:'03/28/1988 23:12:23:323'

SET @ActivityMonitorStartMonth = 45 --CONSIDER LAST FIVE MONTH ACTIVITIES

IF @ActivityMonitorStartDate <> ''
BEGIN	
	SET @ActivityMonitorBeginDate = CAST(@ActivityMonitorStartDate AS DATETIME)
END
ELSE
BEGIN
	SET @ActivityMonitorBeginDate = DATEADD(MONTH, -@ActivityMonitorStartMonth, GETDATE())
END

IF OBJECT_ID('tempdb..#Record') IS NOT NULL
BEGIN
	DROP TABLE #Record	
END

CREATE TABLE #Record
(
	OrderId INT,
	BuildDate DATETIME,
	CustomerId INT
)

INSERT INTO #Record
SELECT Ord.OrderID, Ord.BuildDate, Cus.CustomerID
FROM [Customer] AS Cus
CROSS APPLY
(
	SELECT TOP 1 BuildDate, OrderID 
	FROM [Order]
	WHERE CustomerId = Cus.CustomerID		
	ORDER BY BuildDate DESC
) AS Ord
WHERE Ord.BuildDate < @ActivityMonitorBeginDate

-----------------------------------------------------------------
-- NON ACTIVE CUSTOMER ADDED TO CLEAN PROCESS
-----------------------------------------------------------------
IF OBJECT_ID('tempdb..#CustomerRecord') IS NOT NULL
BEGIN
	DROP TABLE #CustomerRecord
END

CREATE TABLE #CustomerRecord
(	
	CustomerId INT
)

INSERT INTO #CustomerRecord
SELECT C.CustomerID FROM [Customer] AS C
WHERE C.CustomerID NOT IN(
SELECT DISTINCT CustomerID FROM [Order] 
WHERE CustomerID IS NOT NULL) AND C.CreatedDate < @ActivityMonitorBeginDate

DECLARE @CustomerCount INT
SELECT @CustomerCount = COUNT('') FROM #CustomerRecord

IF(@CustomerCount > 0)
BEGIN
	INSERT INTO #Record
	SELECT NULL, NULL, CUS.CustomerId FROM #CustomerRecord AS CUS
END


-- TRANSACTION BEGIN
BEGIN TRAN [CLEAN]

-- BEGIN TRY
BEGIN TRY
	
----------------------------------------------------------------------
-- DELETE ORDER RELATED TABLE
----------------------------------------------------------------------
	-- DELETE ORDER PRINT RECORDS
	PRINT 'DELETE ''OrderPrint'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)	
	DELETE FROM [OrderPrint] WHERE OrderPrintID IN 
	(SELECT O.PickListOrderPrintID FROM [Order] AS O
	JOIN #Record AS R ON O.OrderID = R.OrderID)	
	
	DELETE FROM [OrderPrint] WHERE OrderPrintID IN 
	(SELECT O.MenuOrderPrintID FROM [Order] AS O
	JOIN #Record AS R ON O.OrderID = R.OrderID)	
	PRINT 'DELETE ''OrderPrint'' END. '+ CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE ORDER DAY MEAL RECORDS
	PRINT 'DELETE ''OrderDayMeal'' START. '+ CONVERT(VARCHAR(40),GETUTCDATE(),131)	
	DELETE FROM [OrderDayMeal] WHERE OrderDayID IN
	(SELECT OD.OrderDayID FROM [OrderDay] AS OD
	JOIN #Record AS R ON OD.OrderID = R.OrderID)	
	PRINT 'DELETE ''OrderDayMeal'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE ORDER DAY RECORDS
	PRINT 'DELETE ''OrderDay'' START. '	+ CONVERT(VARCHAR(40),GETUTCDATE(),131)
	DELETE FROM [OrderDay] WHERE OrderID IN
	(SELECT OrderID FROM #Record)	
	PRINT 'DELETE ''OrderDay'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE AGENT NOTE BY ORDER
	PRINT 'DELETE ''AgentNote'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
		
	DELETE FROM [AgentNote] WHERE OrderID IN
	(SELECT OrderID FROM #Record)
	
	PRINT 'DELETE ''AgentNote'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE ORDER 
	PRINT 'DELETE ''Order'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [Order] WHERE OrderID IN
	(SELECT OrderID FROM #Record)
	
	PRINT 'DELETE ''Order'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE ORDER REGENERATION
	PRINT 'DELETE ''OrderRegeneration'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [OrderRegeneration] WHERE OrderID IN 
	(SELECT DISTINCT OrderId FROM #Record)
	
	PRINT 'DELETE ''OrderRegeneration'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE ORDER PAYMENT
	PRINT 'DELETE ''OrderPayment'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [OrderPayment] WHERE OrderID IN 
	(SELECT DISTINCT OrderId FROM #Record)
	
	PRINT 'DELETE ''OrderPayment'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE ORDER DAY MEAL HISTORY
	PRINT 'DELETE ''OrderDayMealHistory'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM OrderDayMealHistory WHERE OrderDayID IN
	(SELECT OrderDayID FROM [OrderDayHistory] AS ODH
	JOIN #Record AS R ON ODH.OrderID = R.OrderId)
	
	PRINT 'DELETE ''OrderDayMealHistory'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE ORDER DAY HISTORY	
	PRINT 'DELETE ''OrderDayHistory'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [OrderDayHistory] WHERE OrderID IN 
	(SELECT DISTINCT OrderId FROM #Record)
	
	PRINT 'DELETE ''OrderDayHistory'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE BULK ORDER HISTORY
	PRINT 'DELETE ''BulkOrderHistory'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [BulkOrderHistory] WHERE OrderID IN 
	(SELECT DISTINCT OrderId FROM #Record)
	
	PRINT 'DELETE ''BulkOrderHistory'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE API REPORT
	PRINT 'DELETE ''ApiReport'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [ApiReport] WHERE OrderID IN 
	(SELECT DISTINCT OrderId FROM #Record)
	
	PRINT 'DELETE ''ApiReport'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
------------------------------------------------------------------------
-- DELETE CUSTOMER RELATED TABLES
------------------------------------------------------------------------	
	-- DELETE CUSTOMER PAYMENT BY CUSTOMERID	
	PRINT 'DELETE ''CustomerPayment'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [CustomerPayment] WHERE CustomerID IN
	(SELECT DISTINCT CustomerId FROM #Record)	
	
	PRINT 'DELETE ''CustomerPayment'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	--DELETE ORDER BY CUSTOMER	
	PRINT 'DELETE ''Order'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [Order] WHERE CustomerID IN
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''Order'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE CUSTOEMR ADDRESS
	PRINT 'DELETE ''CustomerAddress'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [CustomerAddress] WHERE CustomerID IN
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''CustomerAddress'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE AGENT NOTE FOR CUSTOMERID
	PRINT 'DELETE ''AgentNote'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [AgentNote] WHERE CustomerID IN
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''AgentNote'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	--DELETE USERROLES 
	PRINT 'DELETE ''UsersInRoles'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [UsersInRoles] WHERE UserID IN
	(SELECT U.UserID FROM [User] AS U
	JOIN #Record AS R ON U.CustomerID = R.CustomerId)
	
	PRINT 'DELETE ''UsersInRoles'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE BUILD
	PRINT 'DELETE ''Build'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [Build] WHERE UserID IN
	(SELECT U.UserID FROM [User] AS U
	JOIN #Record AS R ON U.CustomerID = R.CustomerId)
	
	PRINT 'DELETE ''Build'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE AGENT NOTE FOR USER
	PRINT 'DELETE ''AgentNote'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	DELETE FROM [AgentNote] WHERE AgentID IN
	(SELECT U.UserID FROM [User] AS U
	JOIN #Record AS R ON U.CustomerID = R.CustomerId)	
	
	PRINT 'DELETE ''AgentNote'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE USER
	PRINT 'DELETE ''User'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [User] WHERE CustomerID IN
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''User'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE VACATION HOLD HISTORY 
	PRINT 'DELETE ''VacationHoldHistory'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [VacationHoldHistory] WHERE CustomerID IN
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''VacationHoldHistory'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE CUSTOMER MEAL
	PRINT 'DELETE ''CustomerMeal'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [CustomerMeal] WHERE CustomerID IN
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''CustomerMeal'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE CUSTOMER INGREDIENT EXCLUSION
	PRINT 'DELETE ''CustomerIngredientExclusion'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [CustomerIngredientExclusion] WHERE CustomerID IN
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''CustomerIngredientExclusion'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE CUSTOMER INGREDIENT EXCLUSION CATEGORY
	PRINT 'DELETE ''CustomerIngredientCategoryExclusion'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [CustomerIngredientCategoryExclusion] WHERE CustomerID IN
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''CustomerIngredientCategoryExclusion'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE CUSTOMER CUSTOMER PLAN HOLD
	PRINT 'DELETE ''CustomerPlanHold'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [CustomerPlanHold] WHERE CustomerPlanID IN 
	(SELECT CP.CustomerPlanID FROM [CustomerPlan] AS CP
	JOIN #Record AS R ON CP.CustomerID = R.CustomerId)
	
	PRINT 'DELETE ''CustomerPlanHold'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE CUSTOMER PLAN
	PRINT 'DELETE ''CustomerPlan'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [CustomerPlan] WHERE CustomerID IN 
	(SELECT CustomerId FROM #Record)
	
	PRINT 'DELETE ''CustomerPlan'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE CUSTOMER ADDRESS BASE CUSTOMER BILLING ADDRESS ID
	PRINT 'DELETE ''CustomerAddress'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [CustomerAddress] WHERE CustomerAddressID IN 
	(SELECT BillingAddressID FROM [Customer] AS CUS
	JOIN #Record AS R ON CUS.CustomerID = R.CustomerId)	
	
	DELETE FROM [CustomerAddress] WHERE CustomerAddressID IN 
	(SELECT ShippingAddressID FROM [Customer] AS CUS
	JOIN #Record AS R ON CUS.CustomerID = R.CustomerId)
	
	DELETE FROM [CustomerAddress] WHERE CustomerID IN 
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''CustomerAddress'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE USER RATING
	PRINT 'DELETE ''UserRatings'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [UserRatings] WHERE CustomerID IN 
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''UserRatings'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE TEMP MEAL QUANTITY
	PRINT 'DELETE ''TempMealQuantity'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [TempMealQuantity] WHERE CustomerID IN 
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''TempMealQuantity'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE TEMP MEAL MERGE
	PRINT 'DELETE ''TempMealMerge'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [TempMealMerge] WHERE CustomerID IN 
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''TempMealMerge'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE TEMP CUSTOM MENU
	PRINT 'DELETE ''TempCustomMenu'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [TempCustomMenu] WHERE CustomerID IN 
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''TempCustomMenu'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE STAGECU
	PRINT 'DELETE ''stagecu'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [stagecu] WHERE CustomerID IN 
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''stagecu'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE PLAN DETAILS
	PRINT 'DELETE ''PlanDetails'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [PlanDetails] WHERE CustomerID IN 
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''PlanDetails'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE MY PROFILE DETAILS
	PRINT 'DELETE ''MyProfileDetails'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [MyProfileDetails] WHERE CustomerID IN 
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''MyProfileDetails'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE MEMBERSHIP LOGIN DETAILS
	PRINT 'DELETE ''MembershipLogin'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [MembershipLogin] WHERE CustomerID IN 
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''MembershipLogin'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE CUSTOMER INGREDIENT EXCLUSION HISTORY
	PRINT 'DELETE ''CustomerIngredientExclusionHistory'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [CustomerIngredientExclusionHistory] WHERE CustomerID IN 
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''CustomerIngredientExclusionHistrory'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE CUSTOMER ACCESS
	PRINT 'DELETE ''CustomerAccess'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [CustomerAccess] WHERE CustomerID IN 
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''CustomerAccess'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE BULK ORDER HISTORY
	PRINT 'DELETE ''BulkOrderHistory'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [BulkOrderHistory] WHERE CustomerID IN 
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''BulkOrderHistory'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	-- DELETE CUSTOM ORDER DAY MEAL
	PRINT 'DELETE ''CustomOrderDayMeal'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [CustomOrderDayMeal] WHERE CustomOrderDayID IN
	(SELECT COD.CustomOrderDayID FROM [CustomOrderDay] AS COD
	JOIN [CustomOrder] AS CO ON COD.CustomOrderID = CO.CustomOrderID
	JOIN #Record AS R ON CO.CustomerID = R.CustomerId)
	
	PRINT 'DELETE ''CustomOrderDayMeal'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)

	-- DELETE CUSTOM ORDER DAY
	PRINT 'DELETE ''CustomOrderDay'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [CustomOrderDay] WHERE CustomOrderID IN
	(SELECT CustomOrderID FROM CustomOrder AS CO
	JOIN #Record AS R ON CO.CustomerID = R.CustomerId)
	
	PRINT 'DELETE ''CustomOrderDay'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)

	-- DELETE CUSTOM ORDER
	PRINT 'DELETE ''CustomOrder'' START. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	DELETE FROM [CustomOrder] WHERE CustomerID IN 
	(SELECT DISTINCT CustomerId FROM #Record)
	
	PRINT 'DELETE ''CustomOrder'' END. ' + CONVERT(VARCHAR(40),GETUTCDATE(),131)
	
	
	
	-- COMMIT THE CHANGES IF NO ERROW HAPPENDS
	COMMIT TRAN [CLEAN]
END TRY
-- CATCH THE ERROR AND ROLLBACK ALL CHANGES
BEGIN CATCH 
	ROLLBACK TRAN [CLEAN]
END CATCH